### ISSUE TITLE
RedisBloom: Support for T-Digest data structure

### ISSUE THREAD

**Issue by filipecosta90** [dengliming/redis-modules-java#20]
Given https://github.com/RedisBloom/RedisBloom/pull/285 there is the following set of commands we should enable:

  - `TDIGEST.CREATE`: Allocate a new histogram
  - `TDIGEST.RESET`: Empty out a histogram and re-initialize it
  - `TDIGEST.ADD`: Add a value to the t-Digest with the specified count
  - `TDIGEST.MERGE`: Merge one t-Digest into another
  - `TDIGEST.CDF`:  Returns the fraction of all points added which are &le; x.
  - `TDIGEST.QUANTILE`: Returns an estimate of the cutoff such that a specified fraction of the data added to the t-Digest would be less than or equal to the cutoff.
  - `TDIGEST.MIN`: Get the minimum value from the histogram.  Will return __DBL_MAX__ if the histogram is empty
  - `TDIGEST.MAX`: Get the maximum value from the histogram.  Will return __DBL_MIN__ if the histogram is empty
  - `TDIGEST.INFO` : Returns compression, capacity, total merged and unmerged nodes, the total compressions 
made up to date on that key, and merged and unmerged weight.

With the in-depth params in https://oss.redislabs.com/redisbloom/master/TDigest_Commands/

**Comment by dengliming** [comment]
@filipecosta90 Seems that the docker version (`redislabs/rebloom:latest`) not support yet. 

`ERR unknown command TDIGEST.CREATE `

**Comment by filipecosta90** [comment]
@dengliming can you try the `redislabs/rebloom:edge`? It should be placed there already

**Comment by dengliming** [comment]
@filipecosta90 Thanks for help. but still not working.

**Comment by filipecosta90** [comment]
@dengliming you're totally right.  `ci/dockercloud-stage Your tests failed in Docker Cloud` failed on dockerhub on the https://github.com/RedisBloom/RedisBloom/pull/285. fixing it and pinging back when all ok

**Comment by filipecosta90** [comment]
@dengliming you should be able to use the `redislabs/rebloom:edge` image. (confirmed it's there :) )
We've just fixed the docker build issue in https://github.com/RedisBloom/RedisBloom/pull/299. 
Thank you for raising this!

**Comment by dengliming** [comment]
Resolved by [https://github.com/dengliming/redis-modules-java/commit/4f35175e1f282af7b417bdc8d87efb75cded34e8](https://github.com/dengliming/redis-modules-java/commit/4f35175e1f282af7b417bdc8d87efb75cded34e8)
