### ISSUE TITLE
Does not work with MsgPackJacksonCodec

### ISSUE THREAD

**Issue by RekaDowney** [dengliming/redis-modules-java#34]
## Question

　　I found that RedisJSON does not support `msgpack`, even though I have specified `MsgPackJacksonCodec`. When executing `JSON.SET` or `JSON.GET`, [io.github.dengliming.redismodule.redisjson.RedisJSON](https://github.com/dengliming/redis-modules-java/blob/master/redisjson/src/main/java/io/github/dengliming/redismodule/redisjson/RedisJSON.java#L115) has been hard-coded to use `StringCodec`. Could you tell me why msgpack is not supported? Because our json object is very large, we hope to use msgpack to compress. Is there any way to support msgpack?

### code

```java

    @Test
    public void test01() throws Exception {
    final Config config = new Config();
    // using msgpack
    config.setCodec(new MsgPackJacksonCodec())
            // single redisjson
            .useSingleServer().setAddress("redis://" + host + ":" + port);

    RedisJSONClient client = new RedisJSONClient(config);
    final String key = "user:redisjson";
    final RedisJSON redisJSON = client.getRedisJSON();
    final ReUser user = ReUser.random();
    redisJSON.set(key, SetArgs.Builder.create(".", JsonUtil.toJson(user)));
    }

```

## Try with Redission

　　I tried to execute the `JSON.SET` command directly through Redission, but the following error was reported. I did not find any related questions in stackoverflow or google. I would appreciate it if you can provide any suggestions.

### code

```java

    @Test
    public void test02() throws Exception {
        String jsonSetScriptCode = "local key = KEYS[1];"
                + "local value = ARGV[1];"
                + "return redis.call('JSON.SET', key, '.', value);";
        final RedissonUser user = RedissonUser.random(1);
        final Object ret = redisson.getScript(codec)
                .eval(
                        RScript.Mode.READ_WRITE,
                        jsonSetScriptCode,
                        RScript.ReturnType.VALUE,
                        Lists.newArrayList("redisson:user" + user.getId()),
                        // new Object[]{objectMapper.writeValueAsBytes(user)}
                        user
                );
        System.out.println(ret);
    }


```

### exception

```text

org.redisson.client.RedisException: ERR Error running script (call to f_fb235438204ece97ce6c81a04f6f210eb59e47f0): @user_script:1: Couldn't parse as UTF-8 string. channel: [id: 0x3aa51975, L:/172.18.53.208:5755 - R:10.3.12.131/10.3.12.131:8080] command: (EVAL), promise: RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@5808a1c9(incomplete)], params: [local key = KEYS[1];local value = ARGV[1];return redis.call('JSON.SET', key, '.', value);, 1, redisson:user1, PooledUnsafeDirectByteBuf(ridx: 0, widx: 258, cap: 512)]

	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)

```

**Comment by dengliming** [comment]
@RekaDowney yeah. currently we use `StringCodec ` in hard-coded. You can try to add your custom `codec ` in SetArgs and modify `setAsync(String key, SetArgs setArgs) ` this method to adapter your scenario. If it work, you can submit a PR. : )

**Comment by RekaDowney** [comment]
> @RekaDowney yeah. currently we use `StringCodec ` in hard-coded. You can try to add your custom `codec ` in SetArgs and modify `setAsync(String key, SetArgs setArgs) ` this method to adapter your scenario. If it work, you can submit a PR. : )

:flushed: I tried but failed in the end. `RedisJSON` currently [does not support msgpack](https://github.com/RedisJSON/RedisJSON/issues/604)

**Comment by dengliming** [comment]
Got it. I'm just doubts that whether it's a good idea to store a `150M` object in RedisJSON.

**Comment by RekaDowney** [comment]
:cry: It is a legacy issue, we will consider refactoring JSON structure and storage, such as multiple separate documents with parent-child relationship.
