### ISSUE TITLE
Highlighting command required a number of fields

### ISSUE THREAD

**Issue by RainGoal** [dengliming/redis-modules-java#53]
Highlighting command required a number of fields,but  after I look up the source code,I don't found the number of fields.
My code is wrong
<img width="741" alt="image" src="https://user-images.githubusercontent.com/60003677/190591788-acaca9be-b4cf-437a-8e2b-e4b9af079411.png">
and
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/60003677/190591915-2f41c538-5f2f-452e-b52f-ee635916d525.png">
The following is the official command documentation
<img width="968" alt="image" src="https://user-images.githubusercontent.com/60003677/190592084-21a39e71-45e5-4ac4-a17c-bc6ca87e6da7.png">

**Comment by RainGoal** [comment]
> Highlighting command required a number of fields,but after I look up the source code,I don't found the number of fields. My code is wrong <img alt="image" width="741" src="https://user-images.githubusercontent.com/60003677/190591788-acaca9be-b4cf-437a-8e2b-e4b9af079411.png"> and <img alt="image" width="1066" src="https://user-images.githubusercontent.com/60003677/190591915-2f41c538-5f2f-452e-b52f-ee635916d525.png"> The following is the official command documentation <img alt="image" width="968" src="https://user-images.githubusercontent.com/60003677/190592084-21a39e71-45e5-4ac4-a17c-bc6ca87e6da7.png">

<img width="929" alt="image" src="https://user-images.githubusercontent.com/60003677/190592500-e8a542bf-a8c0-44b9-815c-cee7b81b39f8.png">
this is your source code

**Comment by dengliming** [comment]
@RainGoal Thanks for reporting this issue. Are you interested in submitting a PR? : )

**Comment by RainGoal** [comment]
> @RainGoal Thanks for reporting this issue. Are you interested in submitting a PR? : )

Yes,I am interested. I will finish it soon

**Comment by RainGoal** [comment]
> @RainGoal Thanks for reporting this issue. Are you interested in submitting a PR? : )

#54 I fix the bug and submit a pull request
