### ISSUE TITLE
升级

### ISSUE THREAD

**Issue by mi1688** [dengliming/redis-modules-java#62]
![image](https://github.com/dengliming/redis-modules-java/assets/32158235/570da64e-526b-4383-aabd-ceac8f60a2e4)

**Comment by dengliming** [comment]
Are you interested in submitting to pr for an upgrade? @mi1688

**Comment by dengliming** [comment]
closed by [https://github.com/dengliming/redis-modules-java/commit/b8a1619e2596e796e729feedd76616889e41853c](https://github.com/dengliming/redis-modules-java/commit/b8a1619e2596e796e729feedd76616889e41853c)
