### ISSUE TITLE
Revrange function not found

### ISSUE THREAD

**Issue by szoke120** [dengliming/redis-modules-java#63]
Hi dengliming!

I'm using your redis modul. It's fantastic, it works very well!
I tried to run revrange command, but it is not implemented yet. Are you planning to add this feature to the libs?

Thanks!

**Comment by dengliming** [comment]
Of course. Do you mean `TS.REVRANGE`?

**Comment by szoke120** [comment]
Yes, I meant the ts.revrange method. Great news that it will be included. I'm looking forward to it! :)

**Comment by dengliming** [comment]
added [https://github.com/dengliming/redis-modules-java/commit/68c78f3f5fe202aabf0dfed262c241848c848a86](https://github.com/dengliming/redis-modules-java/commit/68c78f3f5fe202aabf0dfed262c241848c848a86)
